package de.awais.codingpuzzlestask.deckofcards;

import java.util.ArrayList;
import java.util.List;

public class DeckOfCards {
	// inner class that is datatype for each card
	static class CardType{
		private final String suit;
		private final String rank;
		public CardType(String suit, String rank) {
			this.suit = suit;
			this.rank = rank;
		}
	}
	public static void main(String[] args) {
		String[] suits = {"club", "diamond", "heart", "spade"}; // 4 suits as describe in the puzzle 
		String[] ranks = {"ace", "deuce", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "jack", "queen", "king"}; // 13 ranks as described in puzzle 
		//List to store the all combination of cards
		List<CardType> deckOfCards = new ArrayList<CardType>(); 
		//two nested loops for generating all possible combinations using suits and ranks arrays
		for(String suit:suits) {
			for(String rank:ranks) {
				deckOfCards.add(new CardType(suit, rank)); //add each card into deckOfCards List
			}
		}
		System.out.println("Deck size generated by 4 suits and 14 ranks :: "+ deckOfCards.size()); //Display size of the generated deck of cards which is 52
	}

}
